import type { NodeTypeConfig } from "../../types/index.js";

export const GRID_SIZE = 32;

export const NODE_TYPES: NodeTypeConfig[] = [
  {
    id: "start",
    label: "Start",
    description: "Entry point. Defines the task and workspace context.",
    shape: "rect",
    width: 240,
    height: 88,
    accent: "#16825d",
    fill: "#ffffff",
    border: "#16825d",
    text: "#333333",
    category: "start",
    outputPorts: [],
    defaultConfig: {
      taskDescription: "",
      defaultModel: "gpt-4o",
      defaultProvider: "openai",
    },
  },
  {
    id: "agent",
    label: "Agent Step",
    description: "Configurable AI reasoning step. Select a role (Investigate, Plan, Design, Create, Evaluate, Document) or write a custom system prompt.",
    shape: "rect",
    width: 240,
    height: 100,
    accent: "#5c6bc0",
    fill: "#ffffff",
    border: "#5c6bc0",
    text: "#333333",
    category: "ai-step",
    outputPorts: [],
    defaultConfig: {
      role: "investigate",
      systemPrompt: "",
      model: "gpt-4o",
      provider: "openai",
    },
  },
  {
    id: "review",
    label: "Review",
    description: "Human checkpoint. Pauses the chain until approved or rejected.",
    shape: "rect",
    width: 240,
    height: 88,
    accent: "#e65100",
    fill: "#ffffff",
    border: "#e65100",
    text: "#333333",
    category: "review",
    outputPorts: [
      { id: "approved", label: "Approved" },
      { id: "rejected", label: "Rejected" },
    ],
    defaultConfig: {},
  },
  {
    id: "branch",
    label: "Condition",
    description: "AI evaluates a natural-language condition against the previous output and routes true or false.",
    shape: "rect",
    width: 200,
    height: 80,
    accent: "#78909c",
    fill: "#ffffff",
    border: "#78909c",
    text: "#333333",
    category: "control",
    outputPorts: [
      { id: "true", label: "True" },
      { id: "false", label: "False" },
    ],
    defaultConfig: {
      condition: "",
      provider: "openai",
      model: "gpt-4o",
    },
  },
  {
    id: "fork",
    label: "Parallel",
    description: "Fans the same input out to all connected nodes, running them simultaneously.",
    shape: "rect",
    width: 160,
    height: 64,
    accent: "#7b1fa2",
    fill: "#ffffff",
    border: "#7b1fa2",
    text: "#333333",
    category: "control",
    outputPorts: [],
    defaultConfig: {},
  },
  {
    id: "tool",
    label: "API Request",
    description: "Calls an external HTTP API or webhook.",
    shape: "rect",
    width: 200,
    height: 80,
    accent: "#0097a7",
    fill: "#ffffff",
    border: "#0097a7",
    text: "#333333",
    category: "tool",
    outputPorts: [],
    defaultConfig: {
      url: "",
      method: "GET",
      headers: "{}",
      body: "",
    },
  },
  {
    id: "shell-exec",
    label: "Shell Execute",
    description: "Runs a shell command and captures stdout, stderr, and exit code.",
    shape: "rect",
    width: 200,
    height: 80,
    accent: "#37474f",
    fill: "#ffffff",
    border: "#37474f",
    text: "#333333",
    category: "tool",
    outputPorts: [],
    defaultConfig: {
      command: "",
      workdir: "",
      timeout: 30000,
      outputFormat: "text",
    },
  },
  {
    id: "memory",
    label: "Memory",
    description: "Reads from or writes to a shared memory/context store.",
    shape: "rect",
    width: 200,
    height: 80,
    accent: "#c2185b",
    fill: "#ffffff",
    border: "#c2185b",
    text: "#333333",
    category: "memory",
    outputPorts: [],
    defaultConfig: {
      operation: "read",
      key: "",
    },
  },
  {
    id: "file-write",
    label: "File Write",
    description: "Writes or appends the previous output to a file on disk.",
    shape: "rect",
    width: 200,
    height: 80,
    accent: "#5d4037",
    fill: "#ffffff",
    border: "#5d4037",
    text: "#333333",
    category: "tool",
    outputPorts: [],
    defaultConfig: {
      path: "",
      mode: "write",
    },
  },
  {
    id: "context",
    label: "Context",
    description: "Injects contextual content (URL, file, or text) into connected nodes. Output port is on the right side.",
    shape: "rect",
    width: 200,
    height: 90,
    accent: "#f57c00",
    fill: "#ffffff",
    border: "#f57c00",
    text: "#333333",
    category: "context",
    outputPorts: [],
    defaultConfig: {
      sourceType: "text",
      content: "",
      url: "",
      filePath: "",
      searchQuery: "",
      notes: "",
      spreadToChain: false,
    },
  },
];

export function getNodeType(typeId: string): NodeTypeConfig | undefined {
  return NODE_TYPES.find((t) => t.id === typeId);
}

export function getNodeTypeMap(): Map<string, NodeTypeConfig> {
  return new Map(NODE_TYPES.map((t) => [t.id, t]));
}
