import type { NodeDefinitionV2, NodeV2Type } from "./types.js";

export const GRID_SIZE = 32;
export const INITIALISER_NODE_TYPE: NodeV2Type = "initialiser";
export const SDLC_NODE_TYPES: NodeV2Type[] = ["investigate", "plan", "design", "create", "evaluate", "doc"];

export const NODE_REGISTRY: Record<NodeV2Type, NodeDefinitionV2> = {
  initialiser: {
    type: "initialiser",
    label: "Initialiser",
    defaultTitle: "Initialiser",
    width: 240,
    height: 88,
    accent: "#16825d",
    hasFlowIn: false,
    hasFlowOut: true,
    hasMidputIn: false,
    hasMidputOut: false,
    isSDLC: false,
    defaultConfig: { workspacePath: "./workspace" },
  },
  investigate: {
    type: "investigate",
    label: "Investigate",
    defaultTitle: "Investigate",
    width: 240,
    height: 104,
    accent: "#2d6a9f",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  plan: {
    type: "plan",
    label: "Plan",
    defaultTitle: "Plan",
    width: 240,
    height: 104,
    accent: "#5a3e8c",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  design: {
    type: "design",
    label: "Design",
    defaultTitle: "Design",
    width: 240,
    height: 104,
    accent: "#1a6b4a",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  create: {
    type: "create",
    label: "Create",
    defaultTitle: "Create",
    width: 240,
    height: 104,
    accent: "#8c3e1a",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  evaluate: {
    type: "evaluate",
    label: "Evaluate",
    defaultTitle: "Evaluate",
    width: 240,
    height: 104,
    accent: "#7a3f3f",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  doc: {
    type: "doc",
    label: "Doc",
    defaultTitle: "Doc",
    width: 240,
    height: 104,
    accent: "#3a5a3a",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: true,
    hasMidputOut: false,
    isSDLC: true,
    defaultConfig: { taskPrompt: "" },
  },
  materialize: {
    type: "materialize",
    label: "Materialize",
    defaultTitle: "Materialize",
    width: 240,
    height: 88,
    accent: "#4a4a8a",
    hasFlowIn: true,
    hasFlowOut: true,
    hasMidputIn: false,
    hasMidputOut: false,
    isSDLC: false,
    defaultConfig: {},
  },
  context: {
    type: "context",
    label: "Context",
    defaultTitle: "Context",
    width: 200,
    height: 80,
    accent: "#888888",
    hasFlowIn: false,
    hasFlowOut: false,
    hasMidputIn: false,
    hasMidputOut: true,
    isSDLC: false,
    defaultConfig: { content: "" },
  },
};

export function getNodeDefinition(type: string): NodeDefinitionV2 | null {
  return Object.prototype.hasOwnProperty.call(NODE_REGISTRY, type)
    ? NODE_REGISTRY[type as NodeV2Type]
    : null;
}
